### ISSUE TITLE
LC0005 - Rule0005VariableCasingShouldNotDifferFromDeclaration threw an exception of type 'System.NullReferenceException' - AL Language [v15.0.1177813 (pre-release)]

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#791]
Since today I receive the following warning.

> Analyzer 'BusinessCentral.LinterCop.Design.Rule0005VariableCasingShouldNotDifferFromDeclaration' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0005VariableCasingShouldNotDifferFromDeclaration.AnalyzeTriggerDeclaration(SyntaxNodeAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'

Versions:
- AL Language Extension: v15.0.1177813 (pre-release)

**Comment by Arthurvdv** [comment]
I've did [some rework](https://github.com/StefanMaron/BusinessCentral.LinterCop/pull/781) on this rule in the pre-release version of the LinterCop. Are you getting this error on the latest or pre-release version of LC?

**Comment by ninjaniels** [comment]
Hi,

We just started looking at implementing LinterCop in our DevOps build pipelines, and we are also getting this same warning when compiling the app.
We use ALOps in our build pipelines.

```
steps:
- task: Hodor.hodor-alops.alopsdeploytask.ALOpsAppCompiler@2
  displayName: 'Compile BaseApp'
  inputs:
    artifacttype: Sandbox
    artifactcountry: w1
    alternativevsixurl: Latest
    alsourcepath: app/app.json
    appversiontemplate: '?.?.[yyyyWW].*'
    appfilenametemplate: '%APP_NAME%_%APP_VERSION%_APP.app'
    alcodeanalyzer: BusinessCentral.LinterCop.dll
    resourceexposurepolicy_allowdebugging: Enable
    preprocessorsymbols: 'CLEAN17,CLEAN18,CLEAN19,CLEAN20,CLEAN21,CLEAN22,CLEAN23,CLEAN24'
    publishartifact: false
    failonwarnings: true
```

[LogFile.txt](https://github.com/user-attachments/files/17571468/LogFile.txt)
